[tool.poetry]
name = "chatbots-tails"
version = "0.1.0"
description = ""
authors = ["Taruu <markov2002@bk.ru>"]
readme = "README.md"
packages = [{include = "chatbots-tails"}]



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
